version: "3.8"

services:
  mongodb:
    image: mongo:latest
    container_name: mongodb
    restart: always
    ports:
      - "27017:27017"
    networks:
      - my_network
    volumes:
      - mongo_data:/data/db

  kafka:
    image: confluentinc/cp-kafka:latest
    container_name: kafka
    restart: always
    environment:
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
    ports:
      - "9092:9092"
    networks:
      - my_network

  zookeeper:
    image: confluentinc/cp-zookeeper:latest
    container_name: zookeeper
    restart: always
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
    networks:
      - my_network

  db_service_node1:
    build:
      context: ./node1/component2/db_service
      dockerfile: Dockerfile
    container_name: db_service_node1
    depends_on:
      - mongodb
    networks:
      - my_network
    ports:
      - "50051:50051"

  db_service_node2:
    build:
      context: ./node2/component2/db_service
      dockerfile: Dockerfile
    container_name: db_service_node2
    depends_on:
      - mongodb
    networks:
      - my_network
    ports:
      - "50052:50051"

  node1:
    build:
      context: ./node1
      dockerfile: Dockerfile.node1
    container_name: node1
    depends_on:
      - db_service_node1
    networks:
      - my_network

  node2:
    build:
      context: ./node2
      dockerfile: Dockerfile.node2
    container_name: node2
    depends_on:
      - db_service_node2
    networks:
      - my_network

  api:
    build:
      context: ./component11/api
      dockerfile: dockerfile.api
    container_name: api
    depends_on:
      - kafka
      - db_service_node1
      - db_service_node2
    ports:
      - "8000:8000"
    networks:
      - my_network

  worker:
    build:
      context: ./component11/worker
      dockerfile: Dockerfile.worker
    container_name: worker
    depends_on:
      - kafka
    networks:
      - my_network

networks:
  my_network:
    driver: bridge

volumes:
  mongo_data:
