global:
  scrape_interval: 15s

scrape_configs:
  - job_name: 'api'
    static_configs:
      - targets: ['api:8000']

  - job_name: 'kafka_metrics'
    static_configs:
      - targets: ['kafka:9092']

  - job_name: 'node1_metrics'
    static_configs:
      - targets: ['node1:8080']

  - job_name: 'node2_metrics'
    static_configs:
      - targets: ['node2:8080']

  - job_name: 'mongodb_metrics'
    static_configs:
      - targets: ['mongodb_exporter :27017']