FROM python:3.13.1-slim

WORKDIR /app

RUN pip install fastapi uvicorn requests transformers torch

COPY /worker.py .

EXPOSE 8001

CMD ["uvicorn", "worker:app", "--host", "0.0.0.0", "--port", "8001"]