apiVersion: apps/v1
kind: Deployment
metadata:
  name: node1-deployment
  labels:
    app: node1
spec:
  replicas: 1
  selector:
    matchLabels:
      app: node1
  template:
    metadata:
      labels:
        app: node1
    spec:
      containers:
      - name: node1-container
        image: node1-image
        env:
        - name: NODE_ID
          value: "node1"
        - name: NODE_IP
          value: "178.18.0.2"
        ports:
        - containerPort: 50051
